version: "3"

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    expose:
      - 3306
    networks:
      - inception_net
    env_file:
      - .env
    volumes:
      - database:/var/lib/mysql/
    restart: always


  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    expose:
      - 3306
      - 9000
    networks:
      - inception_net
    env_file:
      - .env
    volumes:
      - wordpress_vol:/var/www/wordpress
    depends_on:
      - mariadb
    restart: always

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    expose:
      - 9000
    ports:
      - 443:443
    networks:
      - inception_net
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - wordpress
    restart: always

networks:
  inception_net:
    driver: bridge

volumes:
  database:
    name: database
    driver_opts:
      device: /home/swang/data/database
      o: bind
      type: none
  wordpress:
    name: wordpress
    driver_opts:
      device: /home/swang/data/wordpress
      o: bind
      type: none
